---
global:
  pattern: multicluster-devsecops

  cicd:
    namespace: devsecops-ci

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  secure-registry:
    namespace: "openshift-storage"

  imageregistry:
    account: css-qe
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: mlabonte-rh
    username: Mark LaBonte
    email: mlabonte@redhat.com
    dev_revision: main

  quay:
    # Needs to be set consistently between hub and spoke clusters
    # TODO: Move back to the hub chart, store in a configmap, have an ACM policy distribute to spoke clusters, have spoke look up from configmap
    org:
      name: devel
      email: devel@myorg.com
    repo: example
  opp: false

main:
  clusterGroupName: hub
